### ISSUE TITLE
ERROR 1017 on EXPO 

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Community/VideoUIKit-ReactNative#100]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [] IOS
   - [X] Android
 - OS Version: [11]

**App Info**
 - Type:
   - [] React Native CLI
   - [X] Expo CLI (using custom development clients)
 - CLI Version: [SDK 45]

**Describe the issue**
Hi! I'm using VideoUIKit-React Native. 
Following the instructions with only Agora Video Code was working fine after doing `expo run:android`, but when I move the code to another screen.. there was an error. Seems to connect fine, but an  Error: 1017 appears. Micro and Camera permissions are asked before open video.

**To Reproduce**
1. Inlcude Video not in main screen.
2. Run `expo run:android`

**Screenshots**
<img width="380" alt="image" src="https://user-images.githubusercontent.com/14013852/203518139-5f337878-8709-4152-aaf9-12253053d53d.png">

**Comment by EkaanshArora** [comment]
Can you reproduce this with the latest version of the UIKit?
