### ISSUE TITLE
How to end call to reciever when sender Ends up the call

### ISSUE THREAD

**Issue by MahmudHasanMenon** [AgoraIO-Community/VideoUIKit-ReactNative#101]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
3. See error

**Screenshots**

**Comment by MahmudHasanMenon** [comment]
@EkaanshArora  please help me.

**Comment by EkaanshArora** [comment]
You'll have to use some form of signalling to let UserA know that UserB has left the call, then you can unmount the UIKit component.
