### ISSUE TITLE
username getting null

### ISSUE THREAD

**Issue by partikshadubb** [AgoraIO-Community/VideoUIKit-ReactNative#103]
![Screenshot 2022-11-25 at 5 01 44 PM](https://user-images.githubusercontent.com/79891951/203976752-39d411f9-dea3-4710-8392-013207eefe18.png)

**Comment by EkaanshArora** [comment]
Did you pass the [username](https://agoraio-community.github.io/VideoUIKit-ReactNative/interfaces/Agora_UIKit.ConnectionData.html#username) in the props? Can you share the JS logs?
