### ISSUE TITLE
dispatching actions twice onPress buttons

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Community/VideoUIKit-ReactNative#104]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. Nexus 5.X]
 - OS:
   - [X] IOS
   - [X] Android
 - OS Version: Android 11

**App Info**
 - Type:
   - [] React Native CLI
   - [X] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 45]

**Describe the issue**
Debugging project, when a button is press, it pass trough reducer twice, so actions dispatch is made twice every single click in a button. It makes no possible to toggle actions state from outside video component,

**To Reproduce**
1. include some console logs in onPress action (in controls) and in reducer
2. Start a video call and click a button
3. See logs

**Screenshots**
<img width="212" alt="image" src="https://user-images.githubusercontent.com/14013852/205043351-9b1bba85-4894-4984-afc0-890193282974.png">

My image is with a custom button, but I try with EndCall button and LocalMuteAudio and same but is occurring.

**Comment by EkaanshArora** [comment]
Can you reproduce this with the latest version of the UIKit? Please make sure the bundling doesn't happen twice, that can cause the component to mount twice if you press `r` twice in quick succession in the metro console.
