### ISSUE TITLE
[Question] - How to move the minView container towards left or right in landscape mode when using pinned layout?

### ISSUE THREAD

**Issue by iamkunall** [AgoraIO-Community/VideoUIKit-ReactNative#106]
Hi! Thank you very much for your great library. We are using the agora react native UI kit in our project. In landscape mode, the minViewContainer overlaps my maxView (selected user). Is there any way I can move the minViewContainer toward left or right so I can see the selected user? Or is there any other way I can fix this view issue? I also tried with grid view but In that. we are unable to select any particular user or focus on them only. thanks.

![2022-12-06 17 18 16](https://user-images.githubusercontent.com/51308694/205903716-2ca2fb5c-7123-42e7-9ae2-e0bc858cbc25.jpg)
![2022-12-06 17 18 25](https://user-images.githubusercontent.com/51308694/205903731-0073198a-17a7-4410-8c41-681b447b98dd.jpg)

**Comment by EkaanshArora** [comment]
You can use the [styleProps](https://agoraio-community.github.io/VideoUIKit-ReactNative/interfaces/Agora_UIKit.StylePropInterface.html) object to move the views around. For example:
```tsx
<AgoraUIKit
        connectionData={connectionData}
        rtcCallbacks={rtcCallbacks}
        styleProps={{
          minViewContainer: {
            marginTop: 10,
          },
          maxViewStyles: {
            marginTop: '50%',
            height: '70%',
            width: '100%',
          },
        }}
      />
```
You can find docs on [minViewContainer](https://agoraio-community.github.io/VideoUIKit-ReactNative/interfaces/Agora_UIKit.StylePropInterface.html#minViewContainer) and [maxViewStyles](https://agoraio-community.github.io/VideoUIKit-ReactNative/interfaces/Agora_UIKit.StylePropInterface.html#maxViewStyles)
