### ISSUE TITLE
Min view container (own camera preview) UI Issue

### ISSUE THREAD

**Issue by HardikTechno** [AgoraIO-Community/VideoUIKit-ReactNative#115]
When we change camera front to rear or rear to front, at that time min view container (own camera preview) width will change, so any solution for this?

**Comment by EkaanshArora** [comment]
Can you add a screenshot or more description on how the UI is changing?

**Comment by HardikTechno** [comment]
@EkaanshArora 
Please check below screenshots
![IMG_0566](https://user-images.githubusercontent.com/85551498/212245596-5c66e4bf-cbae-4d9b-8f39-ae82464c7379.PNG)
![IMG_0565](https://user-images.githubusercontent.com/85551498/212245601-7c11cdb7-d566-4e00-b163-99e69f121f3e.PNG)
