### ISSUE TITLE
Screen Share 

### ISSUE THREAD

**Issue by honey10597** [AgoraIO-Community/VideoUIKit-ReactNative#116]
Hello,

We want to integrate Screen share option in our React Native app in which host can share his screen and audience can view like we do in Google meet and Zoom.

Can you please help us to find the solution.

Thank you.

**Comment by honey10597** [comment]
Hello,

Any update on screen sharing feature ?

**Comment by reactioncompanyapp** [comment]
Is there any progress?

**Comment by EkaanshArora** [comment]
The UIKit builds on top of the [Agora React Native SDK](https://github.com/AgoraIO-Extensions/react-native-agora), we'd have to wait till screen sharing is supported by the SDK.
