### ISSUE TITLE
How to show audio only when call gets started?

### ISSUE THREAD

**Issue by Shweta-UMR** [AgoraIO-Community/VideoUIKit-ReactNative#125]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [ ] IOS
   - [x] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
3. See error

**Screenshots**

**Comment by thvardhan** [comment]
Hi as a fellow struggling with the same issue, I've just made a PR for this #136
