### ISSUE TITLE
Quick start example not working react-native 0.7

### ISSUE THREAD

**Issue by bennaaym** [AgoraIO-Community/VideoUIKit-ReactNative#130]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: Galaxy J7 Prime
 - OS:
   - [ ] IOS
   - [X] Android
 - OS Version: Android 8

**App Info**
 - Type:
   - [X] React Native CLI & NX
   - [ ] Expo CLI (using custom development clients)
 - react-native: 0.70

**Describe the issue**
```js
const App = () => {
  const [videoCall, setVideoCall] = useState(false);
  const connectionData = {
    appId: 'APP_ID',
    channel: 'CHANNEL_NAME',
    token: 'TOKEN'
  };
  const callbacks = {
    EndCall: () => setVideoCall(false),
  };
  return videoCall ? (
    <AgoraUIKit connectionData={connectionData} rtcCallbacks={callbacks} />
  ) : (
    <Text onPress={() => setVideoCall(true)}>Start Call</Text>
  );
};
```

I'm not able to use the quickstart example in my app, when running the app I'm getting the following error: 
```sh
TypeError: Cannot read property 'prefix' of null, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

The error is cause by the <AgoraUIKit /> component removing it my app is working as expected.

**To Reproduce**
1. Run the quick start example : https://www.npmjs.com/package/agora-rn-uikit

**Comment by EkaanshArora** [comment]
Did you install the native dependency? `npm i react-native-agora`, if you're on iOS you'll also have install pods `npx pod-install`.

**Comment by EkaanshArora** [comment]
Can you share your `package.json`?

**Comment by bennaaym** [comment]
@EkaanshArora I found another SDK that worked for me. I will  close this issue. Thank you for help
