### ISSUE TITLE
Import EndCall, MuteAudio, MuteVideo functions

### ISSUE THREAD

**Issue by Garza0** [AgoraIO-Community/VideoUIKit-ReactNative#138]
Hello. Is there a way to import endCall, muteAudio, muteVideo functions? I want replace default buttons and use my own components instead, and call these function on onPress.

**Comment by SanghaPreet** [comment]
Any update on this? @EkaanshArora @Garza0

**Comment by Garza0** [comment]
@SanghaPreet no updates from me. I'm considering using react native agora instead of UIKit, as a workaround I just edited buttons code in the library directly. Still waiting for answer from @EkaanshArora
