### ISSUE TITLE
unable to start rtm  CHANNEL_MESSAGE_ERR_USER_NOT_LOGGED_IN

### ISSUE THREAD

**Issue by srinath116** [AgoraIO-Community/VideoUIKit-ReactNative#142]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [Redmi note 9 pro max]
 - OS:
   - [ ] IOS
   - [X] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [0.69.1]

**Describe the issue**
i have tried enabling rtm to get the active member count in the room
im passing all the necessary props required
> {
  "appId": "XXXX",
  "channel": "XX",
  "layout": 2,
  "rtcToken": ,
  "rtcUid": 
  "rtmToken": 
  "rtmUid": 
}

**To Reproduce**
im using the same  snippet defined in the readme 

**Screenshots**
<img width="584" alt="image" src="https://github.com/AgoraIO-Community/VideoUIKit-ReactNative/assets/26498975/2dc5707f-35bd-43d1-8db4-dc15fb46ebe9">

on Deubgging from node modules 
LOGIN_ERR_INVALID_ARGUMENT this was error in login

**Comment by EkaanshArora** [comment]
are you using the right channel token for RTM?

**Comment by srinath116** [comment]
yes

**Comment by srinath116** [comment]
@EkaanshArora  thanks for the reply can you point me to the python implementation ?

**Comment by srinath116** [comment]
@EkaanshArora  the issue still persists after moving to v2  attaching the props lemme know if im sending something wrong

>  {"appId": "XXXX", 
 "channel": "XXXX", 
"disableRtm": false, 
"layout": 2,
 "rtcToken": "006af4d792267ae4388a7a11165c0b58778IAD1bU5a8tOTjWWtRrH8Myf2eLoZ4toBA5F6tR/Do+dQOyhc33GbjtJtIgA9g7oF9pLIZAQAAQD2kshkAgD2kshkAwD2kshkBAD2kshk", "rtcUid": 3, "rtmToken": "006af4d792267ae4388a7a11165c0b58778IAA9xGipPJI4Umph4EUucLMzRvax/KtVJ8On7aNWEf+Ydfg12E0AAAAAEABeIjgC9pLIZAEA6AP2kshk", 
"rtmUid": 3, 
"token": "006af4d792267ae4388a7a11165c0b58778IAD1bU5a8tOTjWWtRrH8Myf2eLoZ4toBA5F6tR/Do+dQOyhc33GbjtJtIgA9g7oF9pLIZAQAAQD2kshkAgD2kshkAwD2kshkBAD2kshk", 
"uid": 3}

**Comment by bipin-sakariya** [comment]
Video automatic mute when i calling from ios device.
Would you please help me.
