### ISSUE TITLE
onUserJoined callback not working?

### ISSUE THREAD

**Issue by SanghaPreet** [AgoraIO-Community/VideoUIKit-ReactNative#143]
I am following documentation, as per which we have callbacks but I need to know which userJoined, cannot detect this:

Any callback I can use here that can help in knowing which user has joined in:
const rtcCallbacks = {
    EndCall: () => setVideoCall(false),
  };

**Comment by srinath116** [comment]
@SanghaPreet 
you can add a callback on userJoined  

```
 userJoined: ev => {
      console.log(ev, 'userJoined');
    },
```
