### ISSUE TITLE
'connection-state-change' as React UI Kit

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Community/VideoUIKit-ReactNative#151]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [Android]
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [X] Expo CLI (using custom development clients)

**Describe the issue**
Is more a question than an issue. In React UIKit we can use a callback named 'connection-state-change' to create callback when a state is change. 
I have found nothing in React Native UiKit, is there anything similar?

**Comment by EkaanshArora** [comment]
You can find a list of supported events here: https://api-ref.agora.io/en/voice-sdk/react-native/4.x/API/class_irtcengineeventhandler.html#class_irtcengineeventhandler
