### ISSUE TITLE
HELLO TEAM Using Agora UI KIT When I mute my video stream, the video still keeps showing on my local feed. How do I get it to disappear? Do I have to handle it locally by overlaying an image or something?

### ISSUE THREAD

**Issue by varun21s** [AgoraIO-Community/VideoUIKit-ReactNative#69]
HELLO TEAM
Using Agora UI KIT
When I mute my video stream, the video still keeps showing on my local feed. How do I get it to disappear? Do I have to handle it locally by overlaying an image or something?

**Comment by EkaanshArora** [comment]
Updating to v4 of the UIKit should display a black screen with muted icon, when the video is muted. 

I'll expose an API to customize the video placeholder screen in a future release.

**Comment by tungnt-ntq** [comment]
Hi team. 
Using Agora UI KIT
I can't run UI kit on ios
I don't see any special config on ios. except Click File > New > File, select iOS > Swift File, and then click Next > Create to create a new File.swift file.

Don't know on ios need to add any permissions or config?
