### ISSUE TITLE
Callback not working

### ISSUE THREAD

**Issue by srinath116** [AgoraIO-Community/VideoUIKit-ReactNative#80]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: `xiaomi note 9 pro max`
 - OS:
   - [] IOS
   - [X] Android
 - OS Version:22

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [0.69]

**Describe the issue**
RtC call backs are not working with rtm login error 

**To Reproduce**
used the same code mentioned in the documentations

LOGS:
Attempted join:  <channelName>
 LOG  UIkit enabling dual stream undefined
 LOG  Login to RTM
 LOG  join RTM
 LOG  [Error: CHANNEL_MESSAGE_ERR_USER_NOT_LOGGED_IN]
 LOG  Login to RTM
 LOG  join RTM
 LOG  Login to RTM
 LOG  join RTM
LOG LEAVE_CHANNEL_MESSAGE_ERR_USER_NOT_LOGGED_IN

and also how can i remove the names under button icons

**Comment by HalilFocic** [comment]
I am having the same issue,I will let you know if I resolve it. Please do the same as well ❤️

**Comment by srinath116** [comment]
@HalilFocic  you need to pass `disableRtm : true`  in  connectionData props

**Comment by EkaanshArora** [comment]
Are you using tokens?

**Comment by srinath116** [comment]
@EkaanshArora  for  rtc yes

**Comment by EkaanshArora** [comment]
If you want to use features like displaying usernames you can enable RTM and pass in an RTM token with the correct UID.
I'll add removing button text as a feature request.
