### ISSUE TITLE
RtcConnectionData uid doesn't accept string

### ISSUE THREAD

**Issue by LinusU** [AgoraIO-Community/VideoUIKit-ReactNative#81]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: iPhone 11 Pro
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: 16.0

**App Info**
 - Type:
   - [ ] React Native CLI
   - [x] Expo CLI (using custom development clients)
 - CLI Version: SDK 45

**Describe the issue**
The TypeScript typings doesn't allow to pass `uid` as `string`, but I'm using string user ids in my application and the server signs the token with a string `uid`.

**To Reproduce**

```typescript
<AgoraUIKit
  connectionData={{
    appId: '...',
    channel: '...',
    rtcToken: '...',
    // HERE IS THE ERROR
    rtcUid: 'my string user id'
  }}
/>
```

**Screenshots**
n/a

**Comment by EkaanshArora** [comment]
String UIDs are not supported by the UIKit - please use integers.

**Comment by LinusU** [comment]
@EkaanshArora hmm, that is unfortunate since our server workflow tracks our users with string ids. Is there a specific reason why string ids aren't supported? Would a PR to fix this be acceptable, and is it something that I could work on?
