### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeAgora.RtcLocalView.SurfaceView')

### ISSUE THREAD

**Issue by Med-Ahmed-Kilani** [AgoraIO-Community/VideoUIKit-ReactNative#85]
- OS:
   - [] IOS
   - [X] Android
 - OS Version: [8.0.0]

**App Info**
 - Type:
   - [] React Native CLI
   - [X] Expo CLI (using custom development clients)
 - CLI Version: [46.0.6]

**Describe the issue**
Tried to run the example from the uikit description but I'm assuming that there is some incompatible typo with the new version

**Comment by srinath116** [comment]
@Med-Ahmed-Kilani  try downgrading agora version to 3.7.x
