### ISSUE TITLE
Example SurfaceView Error: EXPO DEV CLIENT

### ISSUE THREAD

**Issue by marcsumilang** [AgoraIO-Community/VideoUIKit-ReactNative#90]
![image](https://user-images.githubusercontent.com/47217877/195529206-748684df-c376-42ff-ae36-bd92330816e2.png)
![image](https://user-images.githubusercontent.com/47217877/195529791-0bf22e0a-26dc-4a53-b85f-44eb7a6cb3ef.png)

packages:
    "react": "18.0.0",
    "react-native": "0.69.6",
    "expo": "46.0.13"
    "agora-react-native-rtm": "^1.5.0",
    "react-native-agora": "^4.0.0",
    "agora-rn-uikit": "^4.0.0",
    "expo-dev-client": "~1.2.1",

**Comment by kchurch98** [comment]
Apparently uikit is only supported with react-native-agora <=3.7.x
