### ISSUE TITLE
username is not displayed when passing token to connectionData

### ISSUE THREAD

**Issue by tuledu** [AgoraIO-Community/VideoUIKit-ReactNative#92]
Currently I am having 1 issue about aogra-ui-kit.
If I pass tokenUrl into connectionData, username's displayed.
If I pass token into connectionData, username's not displayed anymore.
I checked in source code, and I see when I pass tokenUrl, then 2 events "MessageReceived" and "ChannelMessageReceived" will be listened, and username will be set,
else if I pass token, then 2 events will be not listened.

Path in this image: agora-rn-uikit/src/RtmConfigure.tsx
it's in init() function
<img width="633" alt="image" src="https://user-images.githubusercontent.com/111717882/196916143-439b7685-f492-4a7b-9aeb-a86beb072de9.png">

Has anyone come across this situation?
This is the version I used:
* "react-native-agora": "^3.5.3"
* "agora-react-native-rtm": "^1.5.0"
* "agora-rn-uikit": "^4.0.0"

**Comment by EkaanshArora** [comment]
are you passing both the RTC & RTM tokens?
