### ISSUE TITLE
[Question] - Is it possible to define the UI Mode like fixed portrait or fixed landscape? 

### ISSUE THREAD

**Issue by JonatanSalas** [AgoraIO-Community/VideoUIKit-ReactNative#97]
Hi! Thank you very much for you great library. I would like to know if its possible to define the encoder config to be fixed in portrait or landscape.

**Comment by EkaanshArora** [comment]
You can [access the engine object](https://github.com/AgoraIO-Community/VideoUIKit-ReactNative/wiki/Guide#advanced-customisation-recomposing-the-ui-kit) from the Agora SDK in the UIKit and use the [setvideoencoderconfiguration](https://api-ref.agora.io/en/voice-sdk/react-native/4.x/API/class_irtcengine.html#api_irtcengine_setvideoencoderconfiguration) method.
